### ISSUE TITLE
Remaining case sensitivity issues on Linux

### ISSUE THREAD

**Issue by dekay** [VitaSmith/cdecrypt#1]
See attached.  If the hex value in the filename before the extension is a letter, the program assumes it will be uppercase and fails.  I manually renamed 0000000d.app to 0000000D.app etc and the program ran successfully.

Thanks for keeping Linux users in mind!  The program works great otherwise.

Edit: I saw a similar report on gbatemp and you reported this fixed.  Just to be clear, I hit this problem on a fresh git pull this afternoon (Jan 1st).  Seems like a lingering bug remains.

![Screenshot_20210101_142416](https://user-images.githubusercontent.com/59916/103445778-1d687380-4c3e-11eb-85b8-c24ff4b4b103.jpg)

**Comment by VitaSmith** [comment]
Thanks for the report. This should be fixed now.

**Comment by dekay** [comment]
Fix works great.  Thanks very much!
