### ISSUE TITLE
Content that doesnt decrypt at alll

### ISSUE THREAD

**Issue by Alecerzea** [VitaSmith/cdecrypt#13]
Fatal Frame Maiden Black Water eshop Game and DLC (these one is detected by cemu even though there are some meta files not decrypted by the tool and causes a crash in the game selection mode)
Tekken Tag 2  Update
Twilight Princess Update
![image](https://user-images.githubusercontent.com/85199063/232138502-3f4e3287-15d0-4b8a-8c0e-8ac2c73bf338.png)
![image](https://user-images.githubusercontent.com/85199063/232138535-076636cb-5dcc-47b7-a353-a9946e5acd8b.png)
![image](https://user-images.githubusercontent.com/85199063/232138981-ae3dea95-e0a6-45e2-bab9-0d633185f4ef.png)
![image](https://user-images.githubusercontent.com/85199063/232138795-9c882296-974e-4782-ab8d-cdf2afaffdd5.png)
After these it crashes

**Comment by Alecerzea** [comment]
It also happens with starfox Zero Update and Kirby and the rainbow curse Update
![image](https://user-images.githubusercontent.com/85199063/232145609-6a33a899-22ad-4bfe-86e7-af8e59dba7f3.png)
![image](https://user-images.githubusercontent.com/85199063/232145645-226789b5-e177-418f-95d3-84a1edd193ce.png)

**Comment by VitaSmith** [comment]
Similar to what I said in #16 I'll accept a patch if someone is willing to contribute one, because I am not planning to look into this personally due to lack of time.
