### ISSUE TITLE
Batch (multiple) NUS folders

### ISSUE THREAD

**Issue by HVR88** [VitaSmith/cdecrypt#2]
Do you have plans to add batch support, perhaps the ability to specify a source folder containing any number of NUS folders and a destination folder to write all the decrypted folders?

Or alternatively, do you have an external script that can batch process as above with your decrypt exe?

The only tool I know of that can handle batch decryption (without downloading) is USB Helper - but that's a little heavy on the UI and database files, plus all the source folders have to be put into its expected locations before they can be used.

**Comment by VitaSmith** [comment]
I have no plans to improve on the application core or add features. My only goal with this project was to clean the existing code and make it compatible with Linux/MacOS.

**Comment by HVR88** [comment]
I probably should have compiled this on my M1 Mac instead of running it on my server's Windows 10 VM. :)

I've written a Windows batch file to handle passing a source PARENT folder to process any number of encrypted folders - destination is the passed folder name with '-decrypted' appended. It works but I'm planning to clean it up a little bit to skip already decrypted content at the destination and add a check to allow distinguishing between a folder of folders or a single encrypted folder.

When I'm done I can post the script to my own repository and link it here if you'd like. I can probably make a bash version as well (probably easier than it was to make the original in Windows batch).

**Comment by whitelancedr** [comment]
i was just wondering HVR88 have you posted cdecrypt with batch support? thank you
