### ISSUE TITLE
Unable to compile - "fatal error: assert.h: No such file or directory"

### ISSUE THREAD

**Issue by JSaterdalen** [VitaSmith/cdecrypt#6]
Compiling on Arch linux (Steam Deck) fails due to missing directories.

**Comment by VitaSmith** [comment]
The issue is with your environment. If a system doesn't have `assert.h` it's definitely not set up for compilation (which is expected from a vanilla Steam Deck).

I see no issue whatsover on Debian or other Linux distros where a gcc toolchain is properly installed:
```
$ make
[C] cdecrypt.c
[C] util.c
[C] aes.c
[C] sha1.c
[L] cdecrypt
```

**Comment by pineguy-64** [comment]
For anyone that runs across this and wants to know how to get the missing headers, Valve removed some files from packages to save room so you need to reinstall 2 files to get these back and be able to compile c++ code. I'm assuming here you've already done the necessary steps to use sudo and install packages (by turning off read-only) on your steam deck.

Reinstall the 2 packages like so:

sudo pacman -S glibc linux-api-headers

Now you should have assert.h and the other missing heading files back.

All credit goes to u/TTachyon for sharing this [on their reddit thread](https://www.reddit.com/r/SteamDeck/comments/t92ozw/for_compiling_c_code/).
