### ISSUE TITLE
Cannot decrypt files randomly

### ISSUE THREAD

**Issue by Xpl0itU** [VitaSmith/cdecrypt#9]
On windows it looks like randomly it will fail to decrypt files, I integrated this cdecrypt fork into my WiiUDownloader program and it has random issues when decrypting on windows for some users, it sometimes work, it sometimes doesn’t 

![96B12DEF-44FD-493E-A47F-425F07B61023](https://user-images.githubusercontent.com/24777100/208304822-d5815868-ab8b-41f0-a210-796565457e6b.png)

**Comment by VitaSmith** [comment]
Looks like the same as #5.

I'm afraid I am not ever going to bother investigating packages that can't be decrypted, as this is a problem with the upstream code I cloned, and my only interest was to provide a version of it that could be compiled on multiple platforms and did not require external dependencies.

If someone else is willing to investigate and propose a patch, I will happily integrate it.
